#!/bin/bash

wget \
    --recursive \
    --no-clobber \
    --page-requisites \
    --html-extension \
    --remote-encoding \
    --convert-links \
    --restrict-file-names=windows \
    --no-parent \
    --wait=20 \
    --random-wait \
    --limit-rate=30K \
    --user-agent='Mozilla/5.0 (Windows NT 6.1; rv:27.3) Gecko/20130101 Firefox/27.3' \
    -e robots=off \
    --domains "$1" \
    "$1"




